### ISSUE TITLE
Could not find com.soywiz.korlibs.korge:korge-box2d:2.0.0-rc2.

### ISSUE THREAD

**Issue by solidogen** [korlibs/kbox2d#9]
https://dl.bintray.com/korlibs/korlibs/com/soywiz/korlibs/korge/korge-box2d/

box2d 2.0.0-rc2 artifact is missing for some reason
I added it by

```
korge {
    supportBox2d()
}
```

Gradle plugin version: 2.0.0.2-rc2
Worked fine on Gradle plugin 1.15.0.0.

Current workaround is swapping `supportBox2d()` with
`dependencyMulti("com.soywiz.korlibs.korge:korge-box2d:2.0.0-alpha", registerPlugin = false)`

**Comment by soywiz** [comment]
Now it is not an artifact but a bundle from https://awesome.korge.org/ that can evolve differently to the plugin.
